{% set name = "flox" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ccadb7b32fec2046c154ae5623b3e646d155077e57b23882619205c7d0588cda

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - importlib-metadata
    - numpy
    - numpy_groupies >=0.9.15
    - pandas
    - python >=3.8
    - toolz

test:
  imports:
    - flox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dcherian/flox
  summary: Fast & furious GroupBy operations for dask.array
  license: Apache-2.0
  license_file: LICENSE

  doc_url: https://flox.readthedocs.io/
  dev_url: https://github.com/dcherian/flox

extra:
  recipe-maintainers:
    - dcherian
