{% set name = "flox" %}
{% set version = "0.8.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bb9cbe6c5544d7a394df6e3aca0bdea02fb3d25c7a296e2aa077262a2708728d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=61
    - setuptools_scm >=7
    - numpy >=1.22
    - numpy_groupies >=0.9.19
    - pandas >=2
    - packaging >=21.3
    - toolz
    - scipy
  run:
    - packaging >=21.3
    - numpy >=1.22
    - numpy_groupies >=0.9.19
    - pandas >=2
    - python >=3.9
    - toolz
    - scipy
  run_constrained:
    - numbagg >=0.6

test:
  imports:
    - flox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xarray-contrib/flox
  summary: Fast & furious GroupBy operations for dask.array
  license: Apache-2.0
  license_file: LICENSE

  doc_url: https://flox.readthedocs.io/
  dev_url: https://github.com/dcherian/flox

extra:
  recipe-maintainers:
    - dcherian
