{% set name = "flox" %}
{% set version = "0.5.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f2cb9b5aca16d6476d72e6a0fe391e1ebfc5ba83f15cf6c07b86e1ef3648a62

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - importlib-metadata
    - numpy
    - numpy_groupies >=0.9.15
    - pandas
    - python >=3.8
    - toolz

test:
  imports:
    - flox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dcherian/flox
  summary: Fast & furious GroupBy operations for dask.array
  license: Apache-2.0
  license_file: LICENSE

  doc_url: https://flox.readthedocs.io/
  dev_url: https://github.com/dcherian/flox

extra:
  recipe-maintainers:
    - dcherian
