{% set name = "flox" %}
{% set version = "0.9.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b184a66cd4d4042b06eeebfbd67d924aa1b478efdd583e85206bcbaea9c851fe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools >=61
    - setuptools_scm >=7
    - numpy >=1.22
    - numpy_groupies >=0.9.19
    - pandas >=1.5
    - packaging >=21.3
    - toolz
    - scipy >=1.9
  run:
    - packaging >=21.3
    - numpy >=1.22
    - numpy_groupies >=0.9.19
    - pandas >=1.5
    - python >=3.10
    - toolz
    - scipy >=1.9
  run_constrained:
    - numbagg >=0.6

test:
  imports:
    - flox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xarray-contrib/flox
  summary: Fast & furious GroupBy operations for dask.array
  license: Apache-2.0
  license_file: LICENSE

  doc_url: https://flox.readthedocs.io/
  dev_url: https://github.com/dcherian/flox

extra:
  recipe-maintainers:
    - dcherian
