{% set name = "flox" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 94652c73b9bd8ef948fd7db97417c0509a8eb68c78518b23422e4fc4bb95dba2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - importlib-metadata
    - numpy
    - numpy_groupies
    - pandas
    - python >=3.7
    - toolz

test:
  imports:
    - flox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dcherian/flox
  summary: Fast & furious GroupBy operations for dask.array
  license: Apache-2.0
  license_file: LICENSE

  doc_url: https://flox.readthedocs.io/
  dev_url: https://github.com/dcherian/flox

extra:
  recipe-maintainers:
    - dcherian
